import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Image
} from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    fontSize: 10,
    paddingTop: 120,
    paddingBottom: 80,
    paddingHorizontal: 40,
    position: "relative"
  },
  header: {
    position: "absolute",
    top: 20,
    left: 40,
    right: 40,
    height: 80,
    border: "1pt solid #ccc",
    backgroundColor: "#f9f9f9",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20
  },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 40,
    right: 40,
    height: 40,
    border: "1pt solid #ccc",
    backgroundColor: "#f9f9f9",
    justifyContent: "center",
    alignItems: "center"
  },
  watermark: {
    position: "absolute",
    top: "35%",
    left: "25%",
    opacity: 0.07,
    width: 300,
    height: 300
  },
  section: { marginBottom: 15 },
  title: { fontSize: 14, marginBottom: 10, fontWeight: "bold" },
  tableRow: { flexDirection: "row", borderBottom: "1pt solid #ccc" },
  cellLabel: { flex: 1, padding: 4, fontWeight: "bold" },
  cellValue: { flex: 2, padding: 4 }
});

// ✅ PDF Component
const KYCUserpdf = () => {
  const userData = {
    kyc_id: "87656544434",
    name: "SajibBaskar Baskar",
    nationality: "India",
    dob: "2011-10-12",
    issued: "2021-07-23",
    created_at: "2025-09-03",
    status: "OCR Verified",
    ocr_id: "784-2011-8493849-2",
    ocr_name_ar: "ساجيف باسكار باسكار",
    ocr_name_en: "SajibBaskar Baskar",
    ocr_dob: "2011-10-12",
    ocr_issue: "2021-07-23",
    ocr_expiry: "2023-06-13",
    ocr_code: "101",
    ocr_nat: "India",
    final_status: "Completed",
    reviewed_by: "admin"
  };

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* ✅ Watermark */}
        <Image style={styles.watermark} src="/AgentVideoKyc/logo.png" />

        {/* ✅ Header */}
        <View style={styles.header}>
          <Image src="/uae_emblem.png" style={{ width: 50, height: 50 }} />
          <View>
            <Text style={{ fontSize: 12, fontWeight: "bold", textAlign: "center" }}>
              United Arab Emirates
            </Text>
            <Text style={{ fontSize: 10, textAlign: "center" }}>
              Federal Authority for Identity and Citizenship
            </Text>
          </View>
          <View>
            <Text>Abu Dhabi, UAE</Text>
            <Text>{new Date().toLocaleString()}</Text>
          </View>
        </View>

        {/* ✅ Footer */}
        <View style={styles.footer}>
          <Text>
            Confidential – For Official Use Only | Generated by Secure KYC Platform
          </Text>
        </View>

        {/* ✅ Title */}
        <Text style={styles.title}>KYC Verification Report</Text>

        {/* ✅ Applicant Info */}
        <View style={styles.section}>
          <Text style={styles.title}>Applicant Information</Text>
          {[
            ["KYC ID", userData.kyc_id],
            ["Name", userData.name],
            ["Nationality", userData.nationality],
            ["Date of Birth", userData.dob],
            ["Issue Date", userData.issued],
            ["Created At", userData.created_at],
            ["Status", userData.status]
          ].map(([label, value], idx) => (
            <View style={styles.tableRow} key={idx}>
              <Text style={styles.cellLabel}>{label}</Text>
              <Text style={styles.cellValue}>{value}</Text>
            </View>
          ))}
        </View>

        {/* ✅ OCR Extracted Details */}
        <View style={styles.section}>
          <Text style={styles.title}>OCR Extracted Details</Text>
          {[
            ["ID Number", userData.ocr_id],
            ["Full Name (Arabic)", userData.ocr_name_ar],
            ["Full Name (English)", userData.ocr_name_en],
            ["Date of Birth", userData.ocr_dob],
            ["Date of Issue", userData.ocr_issue],
            ["Date of Expiry", userData.ocr_expiry],
            ["Issuing State Code", userData.ocr_code],
            ["Nationality", userData.ocr_nat]
          ].map(([label, value], idx) => (
            <View style={styles.tableRow} key={idx}>
              <Text style={styles.cellLabel}>{label}</Text>
              <Text style={styles.cellValue}>{value}</Text>
            </View>
          ))}
        </View>

        {/* ✅ Final Decision */}
        <View style={styles.section}>
          <Text style={styles.title}>Final Decision</Text>
          <View style={{ flexDirection: "row", alignItems: "center" }}>
            <View>
              <Text>Status: {userData.final_status}</Text>
              <Text>Reviewed By: {userData.reviewed_by}</Text>
            </View>
            <Image
              src={userData.final_status === "Completed" ? "/verified.png" : "/rejected.png"}
              style={{ width: 40, height: 40, marginLeft: 20 }}
            />
          </View>
        </View>
      </Page>
    </Document>
  );
};

export default KYCUserpdf;
